config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_in/otp' => 'users/otp/sessions#new'
    post '/users/sign_in/otp' => 'users/otp/sessions#create'
    get '/users/sign_in/recovery_code' => 'users/recovery_code/sessions#new'
    post '/users/sign_in/recovery_code' => 'users/recovery_code/sessions#create'
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root "home#show"
  resource :dashboard, controller: :dashboard
  resource :two_factor_authentication, only: [:show, :create, :destroy] do
    scope module: :two_factor_authentication do
      resource :confirmation, only: [:create, :show]
      resources :recovery_codes, only: [:create, :index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable,
         :otp_secret_encryption_key => ENV['OTP_SECRET_KEY'] || SecureRandom.hex(16)

     
       # Include default devise modules. Others available are:
       # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :registerable,
              :recoverable, :rememberable, :validatable
     
       devise :two_factor_backupable,
              otp_backup_code_length: 8,
              otp_number_of_backup_codes: 12
       
       serialize :otp_backup_codes, JSON
       attr_accessor :otp_plain_backup_codes

       def generate_two_factor_secret_if_missing!
              return unless otp_secret.nil?
              update!(otp_secret: User.generate_otp_secret)
            end
          
       def otp_qrcode
       provision_uri = otp_provisioning_uri(email, issuer: '2FA-Demo')
       RQRCode::QRCode.new(provision_uri)
       end
     end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!
# app/controllers/application_controller.rb
private

def after_sign_in_path_for(resource)
  dashboard_path
end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authenticate_user!
# app/controllers/home_controller.rb
def show
    redirect_to dashboard_path if user_signed_in?
  end
  
end

app/controllers/two_factor_authentication/confirmations_controller.rb
class TwoFactorAuthentication::ConfirmationsController < ApplicationController

    def show
      redirect_to two_factor_authentication_path
    end
  
    def create
      if current_user.validate_and_consume_otp!(params.dig(:otp_code))
        current_user.otp_required_for_login = true
        @recovery_codes = current_user.generate_otp_backup_codes!
        current_user.save!
    
        render "two_factor_authentication/confirmations/success"
      else
        flash.now[:alert] = "Failed to confirm the 2FA code"
        prepare_2fa_form
        render :new
      end
    end
  end

app/controllers/two_factor_authentication/recovery_codes_controller.rb
class TwoFactorAuthentication::RecoveryCodesController < ApplicationController

    def index
      redirect_to two_factor_authentication_path
    end
  
    def create
      @recovery_codes = current_user.generate_otp_backup_codes!
      current_user.save!
      render :index
    end
  end

app/controllers/two_factor_authentications_controller.rb
class TwoFactorAuthenticationsController < ApplicationController
  def show
  end

  def create
    current_user.otp_secret = User.generate_otp_secret
    current_user.save!

    @qrcode = current_user.otp_qrcode
    render 'two_factor_authentication/confirmations/new'
  end

  def destroy
    current_user.otp_required_for_login = false
    current_user.otp_backup_codes&.clear
    current_user.save!
    redirect_to two_factor_authentication_path
  end
end

app/controllers/users/otp/sessions_controller.rb
class Users::Otp::SessionsController < DeviseController
    include OtpSessionExpirable
  
    before_action :expire_otp_session!
  
    prepend_before_action :require_no_authentication, only: [:new, :create]
  
    def new
      unless User.exists?(session[:otp_user_id])
        session[:otp_user_id] = nil
        redirect_to new_user_session_path 
      end
    end
  
    def create
      resource = warden.authenticate!(
        :otp_attempt_authenticatable,
        {
          scope: resource_name,
          recall: "#{controller_path}#new"
        }
      )
  
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  
  end

app/controllers/users/recovery_code/sessions_controller.rb
b
# app/controllers/users/recovery_code/sessions_controller.rb
class Users::RecoveryCode::SessionsController < DeviseController
    prepend_before_action :require_no_authentication, only: [:new, :create]
  
    def new
      unless User.exists?(session[:otp_user_id])
        session[:otp_user_id] = nil
        redirect_to new_user_session_path 
      end
    end
  
    def create
      resource = warden.authenticate!(
        :recovery_code_authenticatable,
        {
          scope: resource_name,
          recall: "#{controller_path}#new"
        }
      )
  
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  
  end
  

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]
  
    # GET /resource/sign_in
    # def new
    #   super
    # end
  
    # POST /resource/sign_in
    def create
      self.resource = warden.authenticate!(:database_authenticatable, auth_options)
  
      if resource.otp_required_for_login?
        sign_out(resource)
        session[:otp_user_id] = resource.id
        session[:otp_user_id_expires_at] = 30.seconds.after
  
        redirect_to users_sign_in_otp_path
      else
        set_flash_message!(:notice, :signed_in)
        sign_in(resource_name, resource)
        respond_with resource, location: after_sign_in_path_for(resource)
      end
    end
  
    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end
  
    # protected
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/two_factor_authentications_helper.rb
module TwoFactorAuthenticationsHelper
end

app/views/dashboard/show.html.erb
<%= link_to "Two-factor authentication", two_factor_authentication_path %>

app/views/home/show.html.erb
<h1>Welcome to 2FA demo </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwoFactorAuthRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <h1>
      <%= link_to '2FA Demo', root_path %>
    </h1>

    <nav>
      <% if user_signed_in? %>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </nav>
  </header>

  <section>
    <% flash.each do |name, msg| -%>
      <%= content_tag :dialog, msg, role: name %>
    <% end %>
  </section>

  <%= yield %>

  <footer>
    <a href="https://rubygems.guide">RubyGems.Guide</a> - 2FA Demo
  </footer>
  </body>
</html>

app/views/two_factor_authentication/recovery_codes/index.html.erb
<h1>Regenerate Recovery Codes Success</h1>

<p>Save this emergency backup code and store it somewhere safe. (All previous codes are expired.)</p>

<ul>
  <% @recovery_codes.each do |code| %>
    <li><%= code %></li>
  <% end %>
</ul>

<%= link_to "Done", two_factor_authentication_path %>

app/views/two_factor_authentications/show.html.erb
<h1>Two-factor authentication</h1>

<h2>Authenticator app</h2>

<% if current_user.otp_required_for_login %>
  <%= button_to "Disable", two_factor_authentication_path, method: :delete %>
<% else %>
  <%= button_to 'Enable', two_factor_authentication_path, method: :post %>
<% end %>

<% if current_user.otp_required_for_login %>
  <h2>Recovery codes</h2>

  <%= button_to "Regenerate", two_factor_authentication_recovery_codes_path, method: :post %>
<% end %>

app/views/users/recovery_code/new.html.erb
<h1>Authenticate your account with a recovery code</h1>

<%= form_with(
      url: users_sign_in_recovery_code_path,
      scope: :user,
      method: :post,
      local: true
) do |f| %>
  <p>To access your account, enter one of the recovery codes you saved when you set up your two-factor authentication device.</p>

  <%= render 'components/otp_field', f: f, field_name: :recovery_code, code_length: 8 %>

  <%= f.submit 'Verify' %>
<% end %>